#!/usr/bin/bash

NC='\e[0m'
BOLD='\e[1m'
UNDERLINE='\e[4m'
BLACK='\e[30m'
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[;33m'
BLUE='\e[34m'

# Background colors
Black='\e[40m'
Red='\e[41m'
Green='\e[42m'
Yellow='\e[43m'
Blue='\e[44m'
Magenta='\e[45m'
Cyan='\e[46m'
White='\e[47m'

prerequisites=(
  "git"
  "curl"
  "wget"
  "zsh"
  "tmux"
  "fzf"
  "unzip" # Yazi would use unzip
)

echo -e "${YELLOW}Checking prerequisites...${NC}"
for item in ${prerequisites[@]}; do
  if ! command -v "${item}" >/dev/null 2>&1; then
    echo -en "${RED}Doesn't find "${item}". Install now?${NC} [${UNDERLINE}Y${NC}/n] "
    read -r install
    if [ -z ${install} ]; then
      install="Y"
    fi
    if [ ${install} == "Y" ]; then
      echo -en "Select a package manager(apt|dnf): "
      read -r PACKAGE_NAMAGER
      if [ $PACKAGE_NAMAGER == "apt" ]; then
        echo "Using apt"
        sudo apt install ${item}
      elif [ $PACKAGE_NAMAGER == "dnf" ]; then
        echo "Using dnf"
        sudo dnf install ${item}
      else
        echo "Unsupported package manager."
        exit 1
      fi
    else
      echo -e "${RED}Initialization failed${NC}"
      exit 1
    fi
  fi
done
echo -e "${GREEN}All prerequisites have been met${NC}"

# Setup SSH key to Github
echo -en "Do you want to generate ssh-key to github now?[${BOLD}${UNDERLINE}Y${NC}/n]:"
read -r github_ssh
if [ -z ${github_ssh} ]; then
  github_ssh="Y"
fi
if [ ${github_ssh} = "Y" ]; then
  if [ -f "${HOME}"/.ssh/id_ed25519 ]; then
    echo -e "${YELLOW}Key already exists.${NC}"
  else
    echo -en "Your email: (To connect to Github using ssh):"
    read Email
    ssh-keygen -t ed25519 -C "${Email}"
  fi
  echo -e "${GREEN}The public key is:${NC}"
  cat "${HOME}"/.ssh/id_ed25519.pub
fi

# Get Oh-my-zsh
if ! [ -d "${HOME}"/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Get zsh plugins
echo -e "${YELLOW}Getting oh-my-zsh plugins...${NC}"
. plugins.zsh

# Configure LazyVim
git clone https://github.com/FSReed/nvim "${HOME}"/.config/nvim

# Execute the sync script
echo -e "${BLUE}Synchronizing config files...${NC}"
. sync_script

# Install neovim, and some useful tools
. tools.install

echo -e "All Done!"
echo -e "Reconnect to terminal then type ${GREEN}source \"\${HOME}\"/.zshrc${NC} to work with a brand new shell!"
