#!/usr/bin/bash

if ! command -v git > /dev/null 2>&1; then
    echo "You need to install git first"
    exit 1
fi

if ! command -v zsh > /dev/null 2>&1; then
    echo "You need to install zsh first"
    exit 1
fi

NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
BLACK='\033[30m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[;33m'
BLUE='\033[34m'

# Background colors
Black='\033[40m'
Red='\033[41m'
Green='\033[42m'
Yellow='\033[43m'
Blue='\033[44m'
Magenta='\033[45m'
Cyan='\033[46m'
White='\033[47m'

# Setup SSH key to Github
echo -en "Do you want to generate ssh-key to github now?[${BOLD}${UNDERLINE}Y${NC}/n]:"
read -r github_ssh
if [ -z "$github_ssh" ]; then
    github_ssh="Y"
fi
if [ "$github_ssh" = "Y" ]; then
    if [ -f ~/.ssh/id_ed25519 ]; then
        echo -e "${YELLOW}Key already exists.${NC}"
    else
        echo -n "Your email: (To connect to Github using ssh):"
        read Email
        ssh-keygen -t ed25519 -C "$Email"
    fi
    echo -e "${GREEN}The public key is:${NC}"
    cat ~/.ssh/id_ed25519.pub
fi

# Get Oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Get Plugins

# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Execute the sync script
echo -e "${BLUE}Synchronizing config files...${NC}"
chmod 700 sync_script
./sync_script

echo -e "All Done!"
echo -e "Type ${White}${BLACK}source ~/.zshrc${NC} to start with brand new bash!"
