#!/usr/bin/bash

if ! command -v git > /dev/null 2>&1; then
    echo "You need to install git first"
    exit 1
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'

echo -en "Do you want to generate ssh-key to github now?[${BOLD}${UNDERLINE}Y${NC}/n]:"
read -r github_ssh
if [ -z "$github_ssh" ]; then
    github_ssh="Y"
fi
if [ "$github_ssh" = "Y" ]; then
    if [ -f ~/.ssh/id_ed25519 ]; then
        echo -e "${RED}Key already exists.${NC}"
    else
        echo -n "Your email: (To connect to Github using ssh):"
        read Email
        ssh-keygen -t ed25519 -C "$Email"
    fi
    echo -e "${GREEN}The public key is:${NC}"
    cat ~/.ssh/id_ed25519.pub
fi

# Execute the sync script
echo -e "${GREEN}Synchronizing config files...${NC}"
./sync_script

echo -e "All Done!"

