#!/usr/bin/bash

files_to_sync=(
    ".bashrc"
    ".vimrc"
    ".tmux.conf"
    ".gitconfig"
    # Need special operation:
    "plug.vim"
)

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

for item in "${files_to_sync[@]}"; do
    echo -e "${BLUE} Syncing ${item}"
    rsync -vh ./"$item" ~/ > /dev/null 2>&1
done

# Sync Plug.vim
plug_vim_path="$HOME/.vim/autoload/"
if ! [ -d "$plug_vim_path" ]; then
    echo -e "${GREEN}No .vim folder under home directory. Creating one...${NC}"
    mkdir -p "$plug_vim_path"
fi

mv "$HOME"/plug.vim "$plug_vim_path"

echo -e "${GREEN}All config files are synchronized${NC}"

