#!/usr/bin/bash

Config_Dir="./config"

config_files=(
    # Into Home Directory
    ".bashrc:${HOME}"
    ".zshrc:${HOME}"
    ".vimrc:${HOME}"
    ".tmux.conf:${HOME}"
    ".gitconfig:${HOME}"
    # Special Path
    "aliases.zsh:${ZSH}/custom"
    "functions.zsh:${ZSH}/custom"
)

NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'

# Background colors
Black='\033[40m'
Red='\033[41m'
Green='\033[42m'
Yellow='\033[43m'
Blue='\033[44m'
Magenta='\033[45m'
Cyan='\033[46m'
White='\033[47m'

for item in ${config_files[@]}; do
    name=$(echo ${item} | cut -d: -f1)
    path=$(echo ${item} | cut -d: -f2)
    echo -e "Do you want to sync ${YELLOW}${UNDERLINE}${name}${NC}?"
    echo -en "${RED}CAUTION:${NC}This will overwrite the original file![Input ${BOLD}${UNDERLINE}N${NC} to stop syncing.]:"
    read choice
    if  [[ ${choice} == "N" ]]; then
        echo -e "${YELLOW}Doesn't sync ${UNDERLINE}${name}${NC}"
        continue
    fi

    # Use hard link
    echo -e "${GREEN}Copying ${name} into ${path}${NC}\n"
    cp ${Config_Dir}/${name} ${path}
done

echo -e "${GREEN}Finish synchronization.${NC}"

