#!/usr/bin/bash

files_to_sync=(
    ".bashrc"
    ".zshrc"
    ".vimrc"
    ".tmux.conf"
    ".gitconfig"
    # Need special operation:
    "plug.vim"
    "aliases.zsh"
)

NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'

# Background colors
Black='\033[40m'
Red='\033[41m'
Green='\033[42m'
Yellow='\033[43m'
Blue='\033[44m'
Magenta='\033[45m'
Cyan='\033[46m'
White='\033[47m'

for item in "${files_to_sync[@]}"; do
    if [ "$item" == ".bashrc" || "$item" == ".zshrc" ]; then
        echo -e "${YELLOW}Do you want to sync "$item"?${NC}"
        echo -en "${RED}CAUTION:${NC}This will overwrite the original file![${BOLD}${UNDERLINE}${Cyan}Y${NC} to confirm overwrite]:"
        read choice
        if ! [ "$choice" == "Y" ]; then
            echo -e "${YELLOW}Synchronization of .bashrc is cancelled.${NC}"
            continue
        fi
    fi
    echo -e "${BLUE} Syncing ${item}${NC}"
    rsync -vh ./"$item" ~/ > /dev/null 2>&1
done

# Sync Plug.vim
plug_vim_path="$HOME/.vim/autoload/"
if ! [ -d "$plug_vim_path" ]; then
    echo -e "${GREEN}No .vim folder under home directory. Creating one...${NC}"
    mkdir -p "$plug_vim_path"
fi
mv "$HOME"/plug.vim "$plug_vim_path"

# Sync oh-my-zsh settings

# Sync aliases.zsh
mv "$HOME"/aliases.zsh "$ZSH_CUSTOM"/

echo -e "${GREEN}All config files are synchronized${NC}"
