# Install neovim, and some useful tools

## Install the newest version of neovim
echo -e "Installing neovim into /opt..."
wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo tar -C /opt -xzf nvim-linux64.tar.gz
echo "PATH=/opt/nvim-linux64/bin:\${PATH}" >> ${HOME}/.profile
rm nvim-linux64.tar.gz
echo -e "Neovim Installed."

sudo apt-get update

## Install some useful tools
sudo apt-get install ranger
sudo apt-get install fzf

